### ISSUE TITLE
TABLE.Replacement

### ISSUE THREAD

**Issue by Yasnen** [BrotherSharper/foundryVTTja#1]
ja.json
"TABLE.Replacement": "ダイスロール毎に、同じ結果が出るようにする"
"TABLE.ToggleDrawn": "ロール結果のロック",

原文は
"TABLE.Replacement": "Draw with Replacement?",
"TABLE.ToggleDrawn": "Toggle Drawn Status",

動作を見る限りでは、多分違う意味だと思われる。
テーブルの「鍵」マーク、マウスホバーで（"TABLE.ToggleDrawn": "Toggle Drawn Status",）が表示される。は
「鍵」マークがある項目のみからロール結果が選択される。

"TABLE.Replacement"のチェックが無い場合、出た目の「鍵」マークが消える。

前者は
・チェック有り：普通のロール表として処理される
・チェック無し：ロールすると出た目の「鍵」マークが外れる。「鍵」マークが一つも無いとロールはエラーになる。これはロールテーブルをカードに見立てて、カードを引く＝Drawって機能じゃないかな。リセットボタンを押下するとすべての「鍵」が復活する。

これが正しい場合、どういう日本語にすると良いのか、悩ましい。

**Comment by BrotherSharper** [comment]
ありがとうございます、

あんまり使われている機能じゃないのでだいぶ放置されていましたね。
この機能は鍵マークがあるとロール時に選出されないようにするためのものです。主な使い方は：
- 同じ結果を出さないため
- ランダムと見せかけて確定のものしか出ないようにする
等です。

今のままだと正しい動作の説明にはなっていないので…

"TABLE.Replacement": "同じ結果を繰り返し表示しても良い",
"TABLE.ToggleDrawn": "既出状態切り替え",

あたりにしたいと思います。
それか「ロール後、既出状態にしない」あたりも良いかもしれませんが、次のアップデートに考えてきます。

もし上の様に動作しない場合はシステム独自の仕様が入っているかも？その場合は教えてください。

**Comment by Yasnen** [comment]
その訳であれば動作と説明が整合していると思います。
原文廚な身としては、Drawからカードを引く的なニュアンスを込めたいところですが、それは別の話なので、Closeしてくださいｗ

**Comment by BrotherSharper** [comment]
了解です、ご協力ありがとうございました！
