### ISSUE TITLE
 "KEYBINDINGS.*"

### ISSUE THREAD

**Issue by Yasnen** [BrotherSharper/foundryVTTja#2]
言語ファイルのキーバインドの設定画面部分を見始めましたが、間違いが有ります。

１．"KEYBINDINGS.ExecuteMacro"
"KEYBINDINGS.ExecuteMacro": "ホットバーからマクロを実行",
"KEYBINDINGS.ExecuteMacro": "Execute Hotbar Slot {number}",

{number}でホットバーに示されている番号が指定されるのに、抜けている。
"KEYBINDINGS.ExecuteMacro": "ホットバーからマクロ{number} を実行",

２．"KEYBINDINGS.SwapMacroPage": "Swap to Hotbar Page {page}",
ja.langに存在しない。
"KEYBINDINGS.SwapMacroPage": "ホットバーをページ{page} に切替",

こんな感じで修正した方が良いかと思います。

**Comment by BrotherSharper** [comment]
報告ありがとうございます！
こちらはv9の途中のアップデートで仕様が変わって追加されたものですので次のリリースでアップデート予定です。（もっと早めにやっておけば良かったけど完全に忘れてました）

**Comment by Yasnen** [comment]
追加
  "CONTROLS.ObjectRotateSlow": "オブジェクト (遅い)",
  "CONTROLS.ObjectRotateFast": "オブジェクト (速い)",

両方ともオブジェクトの回転速度なので、「オブジェクト」⇒「オブジェクトの回転」
マウスホイール1クリックでオブジェクトの回転する角度大きいか、小さいかの違いですね。

**Comment by Yasnen** [comment]
キーバインド周りで見つかったのは以上でした。
自分の言語ファイルも作り終えたので、見落としあるかもしれませんが、しばらくは追加指摘は無いはずです。

**Comment by BrotherSharper** [comment]
ありがとうございます、こちらも修正しておきます
