### ISSUE TITLE
他モジュールに対するローカライズ時の用語について

### ISSUE THREAD

**Issue by Yasnen** [BrotherSharper/foundryVTTja#3]
# 前提となる条件の確認

「オンセ工房」という表現について
貴方のモジュールではFoundry Virtual Tabletop(以下、FVTTと略す)をオンセ工房FVTTと表示している。この表示は日本でのFoundry Virtual Tabletopの公式な名称ではない。また、貴方のコミュニティの名称でもあり、コミュニティ外での利用はネガティブである。基本的には「オンセ工房」は貴方のコミュニティとそのコントロール下で使用されるべき名称である。

貴方は様々なモジュールに対してローカライズで貢献しており、そのローカライズで「FVTT」を「オンセ工房」という表示をしたり、「オンセ工房FVTT」でのローカライズに合わせたローカライズ用語を使用しています。残念ながら、全てのモジュールをローカライズしているわけではないし、アップデートにたいして完璧に対応できているとも言い難いのが現状と思います。

ここの認識に間違いがあると、以下の提案も考え方を見直す必要もあるかもしれないので、予めご確認お願いします。

# 提案内容

当方はローカライズが未実施であったりアップデートに対応していないモジュールにたいして、修正のプルリクエストをかけていますが、その際に懸念点が有るので可能な範囲で確認＆合意をしたいので以下の通り提案します

## １．「オンセ工房」表記について
貴方のコントロール下に無いモジュールへのローカライズする場合に、FVTTを「オンセ工房」表記は使用しない。
（考え方）「FVTT」＝「オンセ工房FVTT」ではないので、利用する人がそのように誤解することは避けるべき
（想定される問題点）当方のFVTTやWFRP4eシステムをローカライズするモジュールは「オンセ工房」のローカライズとは関係なくローカライズしており、何か問題（誤訳などによる）が起きたときに対応する責任は当方に有ると考えておりますが、使用されるモジュールに「オンセ工房」表記があると、当方ではなく「オンセ工房」に問い合わせが行く可能性がある。

## ２．ローカライズの用語について
全てのモジュールをローカライズできるわけでもないので、特に、FVTT公式のAPIで定義されているクラスなどの単語については、誤認識されるような表現は避けるべきと考えています。
https://foundryvtt.com/api/
そのレベル感としては、当方視点では三つあると考えており
(1)深刻
他の用語と混同されることにより、利用する人が誤解を受けるため、基本的に他の用語と混同される表現は避けて、基本的に同じ日本語を使うべき。（前項の「オンセ工房」もこのカテゴリと考えています。）
(2)要検討
元の用語と関連が薄く、ローカライズされていないモジュールを使う・探す時に混乱するため、可能な範囲で同じ表現をすべき。
(3)問題無し
元の用語を想像でき、表現上の違いが趣味レベルである。同じ表現が望ましいが合わせる必要は無し。

その観点では、WFRP4eシステムでは「Actor」を「キャラクター」とローカライズしているのは、「Character」という用語が別にあるため許容できず、(1)に相当すると考えております。また、ActorのタイプにVehcileもあり、キャラクターとローカライズされるのは違和感があります。

「Actor＝キャラクター」については、「オンセ工房」コミュニティで一回問題提起しましたが、以前に十分議論したので変更は受け入れられないとの回答でしたが、当方の理解も進んだ上での再度の問題提起になります。以前に十分議論した議論の内容については示されていないので、それをお示しいただくか、WFRP4eシステムに対する影響を加味した判断・回答をお願いします。リーズナブルな合意が出来ればと考えております。

(1)は他に有りませんが、「Token＝コマ」が(2)に相当し、「Token⇒トークン」が適切と思いますが、「コマ」とローカライズすべき理由をご教示いただきれば、そちらに合わせるか否か判断できるのでよろしくお願いします。

### 当方提案

上に書いた内容をシンプルに箇条書きにすると以下の通りです

-「Actor⇒アクター」とローカライズすべき

-「Token⇒トークン」とローカライズする方が望ましい

## 当面の対応

当方としては、他のモジュールに対してアップデート未対応で未訳があったり誤訳へローカライズのプルリクエストをかける場合、２．で示したレベル感毎に、以下の対応をするつもりです。

(1)深刻
既訳部分についても当方の判断に基づいて全て修正します。

(2)要検討、(3)問題無し
未訳、誤訳部分の修正を実施し、既訳部分は修正箇所と整合性がとる必要がある場合のみ修正します。

**Comment by BrotherSharper** [comment]
申し訳ありません、内容を読ませていただきましたが、APIの利用を行うユーザとAPIと無縁（むしろ忌避）する一般ユーザの認識の区別がなされていませんので、この提案は受け入れられません。

あらためて、オンセ工房は海外の他のコミュニティとも話をした上で決めたものです。ドイツ語、フランス語も同じ様に国ごとの名称を決めて運用しています。

「ローカライズ」という言葉はその国の文化や国柄を理解して翻訳作業を行うことです。そちらのやっていることは原文の翻訳です。どちらも明確なメリットとデメリットが存在するものですが、私の管理するところにおいては「ローカライズ」を選んでおります。

翻訳を提供いただくのはとてもありがたいですし、私に許可を取る必要もありません。受け入れるかどうかはそのリポジトリの作者ですので、もし使っていく上で不適切な翻訳があればこちらもプルリクを出したり作者と相談するだけです。

こちらからお願いが一つあるとすれば、どうかBrother Sharpが関わっていない翻訳については必要以上の前の人の訳を変えないであげてください。少し見ただけですが、tougeさんが頑張って翻訳したdrag-rulerの翻訳者名をja.jsonから消しているのを確認しました。
![image](https://user-images.githubusercontent.com/41280723/174424017-dd3d978c-2612-4014-ad18-96f96db7106e.png)

こういう場合は自分の名前を併記してください。あなただけが唯一の貢献者ではありません。

ご覧の通り他人が提出したものについても私も私の思想を押し付けていませんので、あなたの思想（原文オンリー）を押し付けないでください。もしコマやキャラという名称が使われているのならば、それはそのユーザが共感して併記して頂いたものであり、あなた以外の人が問題提起をしていないのであれば「好まれて使われている」こともご考慮ください。

私から言えることは以上です。

**Comment by Yasnen** [comment]
モジュールを探す際に、API名は意識せざるを得ません。FVTTを使用する人はAPIの名称に無関係という荒唐無稽な反論で理解に苦しみます。とはいえ、受け入れられないということであれば、了解しました。

１．についての懸念は、当方のmodに「オンセ工房」表記があるモジュールを使っていたら、利用している人は「オンセ工房」と勘違いして、そちらに問い合わせるのではないかなと懸念してました。当方は全く困りませんが。
また、海外のコミュニティと相談して決めた。ということがどういう意味を持つのか全く理解不能です。
「FVTTオンセ工房」が日本でのオフィシャルな名称ということでしょうか？
違うのであればご説明お願いします。

最後のお願いについては、明確に「ノー」とお答えします。言語ファイルの中に使われない、それどころか想定外の動作が発生する懸念もあるのでキーが使われることを当方はヨシとしません。少なくとも「Localization Provided By」などと言うキーは当方には断じて認められません。
なお、貢献については、プルリクのなかで名前が挙がり、そこで示されることで十分果たせているとの認識です。

これも最終的には作者の判断にお任せします。

また押し付けたのではなく、落としどころが無いのか提案をさせていただいたにも関わらず、荒唐無稽な反論で既存のローカライズが正しいという主張を押し付けられるのは、極めて遺憾です。
誤：あなた以外の人が問題提起をしていないのであれば「好まれて使われている」
正：問題提起をするほど問題意識を持っていない

**Comment by BrotherSharper** [comment]
翻訳はユーザのためのものです。同じ視座を共有出来ないのは残念です。

私の反論を荒唐無稽と言いながらもModを好んで使っている人を「問題意識を持っていない」は陰謀論者のすることです。誰もあなたの攻撃していませんので、どうか頭を冷やしてください。私が嫌いなのはよく分かりましたが、ウォーハンマーのコミュニティの人たちと相談して全員の意見をまとめて見てください。
（私は指摘頂いた通り色んな人にアドバイスをもらいながらもコマやキャラの表記が好まれていることを知りました）

そちらがヨシとしなくてもJsonの中にコメント文を入れることはれっきとした技術的な手法です。こちらは作者とも相談をしながら入れていただいているものです。あなた一人ではなく、色んな人の翻訳のモチベーションが保たれるように視野を広めてご活動ください。

上でも申し上げたとおり、客観的に不適切な内容（今回のキーの削除や用語をウォーハンマーしか通用しないものにしたり）などは作者と話をしながらより適切なものをこちらが対応しますので、気になさらずに翻訳作業を続けてください。

**Comment by Yasnen** [comment]
嫌いなのは、貴方の**人の意見を全く聞かない**ところですので、お間違え無く。
